#!/bin/bash

# Install Homebrew
if [ ! -f /usr/local/bin/brew ]; then
	echo "Installing homebrew"
	/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
	echo "Homebrew installed successfuly"
fi

# Install zsh
sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

# Install pathogen.vim
if [ ! -d ~/.vim ]; then
	echo "Installing pathogen..."
	mkdir -p ~/.vim/autoload ~/.vim/bundle && \
	curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim
	echo "Pathogen.vim installed successfuly!"
fi

# Install vim-rails
if [ ! -d ~/.vim/bundle/vim-rails ]; then
	echo "Installing vim-rails plugin..."
	cd ~/.vim/bundle && git clone https://github.com/tpope/vim-rails.git && vim -u NONE -c "helptags vim-rails/doc" -c q
	echo "vim-rails installed successfuly!"
fi

# Install bundler ...
if [ ! -d ~/.vim/bundle/vim-bundler ]; then
	echo "Install bundler.vim ..."
	cd ~/.vim/bundle && \
	git clone git://github.com/tpope/vim-bundler.git
	echo "bundler.vim installed successfuly"
fi

# Install dispatcher.vim
if [ ! -d ~/.vim/bundle/vim-dispatch ]; then
	echo "Install dispatcher.vim"
	cd ~/.vim/bundle && \
	git clone git://github.com/tpope/vim-dispatch.git
	echo "dispatcher.vim installed successfuly"
fi

# Install auto-pairs...
if [ ! -d ~/.vim/bundle/auto-pairs ]; then
	echo "Install auto-pairs.vim"
	git clone git://github.com/jiangmiao/auto-pairs.git ~/.vim/bundle/auto-pairs
	echo "auto-pairs.vim installed successfuly"
fi

# Install tlib.vim
if [ ! -d ~/.vim/bundle/tlib_vim ]; then
	echo "Install tlib.vim..."
	cd ~/.vim/bundle && \
	git clone https://github.com/tomtom/tlib_vim.git
	echo "tlib installed successfuly"
fi

# Install vim-addon-mw-utils
if [ ! -d ~/.vim/bundle/vim-addon-mw-utils ]; then
	echo "Install vim-addon-mw-utils.vim"
	cd ~/.vim/bundle && \
	git clone https://github.com/MarcWeber/vim-addon-mw-utils.git
	echo "vim-addon-mw-utils installed successfuly"
fi

# Install vim-snipmate
if [ ! -d ~/.vim/bundle/vim-snipmate ]; then
	echo "Install vim-snipmate"
	git clone https://github.com/garbas/vim-snipmate.git
	echo "vim-snipmate installed successfuly"
fi

# Install vim-snippets
if [ ! -d ~/.vim/bundle/vim-snippets ]; then
	echo "Install vim-snippets..."
	git clone https://github.com/honza/vim-snippets.git
	echo "vim-snippets installed successfuly"
fi

# Install sensible.vim
if [ ! -d ~/.vim/bundle/vim-sensible ]; then
	echo "Install vim-sensible"
	cd ~/.vim/bundle && \
	git clone https://github.com/tpope/vim-sensible.git
	echo "vim-sensible installed successfuly"
fi

# Install colorschemes
if [ ! -d ~/.vim/bundle/colorschemes ]; then
	echo "Install colorschemes...."
	cd ~/.vim
	git clone https://github.com/flazz/vim-colorschemes.git bundle/colorschemes
	echo "colorschemes installed successfuly"
fi

# Install nerdtree
if [ ! -d ~/.vim/bundle/nerdtree ]; then
    echo "Install nerdtree..."
    git clone https://github.com/scrooloose/nerdtree.git ~/.vim/bundle/nerdtree
    echo "nerdtree installed successfuly"
fi

# Install ctags
if [ -f /usr/local/bin/brew ]; then
    echo "Install ctags from homebrew"
    brew install ctags
    echo "ctags successfuly installed"
fi

# Install vim-markdown-preview
if [ ! -d ~/.vim/bundle/vim-markdown-preview ]; then
    echo "Install vim-markdown-preview"
    brew install grip
    cd ~/.vim/bundle && \
    git clone https://github.com/JamshedVesuna/vim-markdown-preview.git
    echo "vim-markdown-preview installed successfuly" 
fi

# Install emmet-vim
if [ ! -d ~/.vim/bundle/emmet-vim ]; then
    echo "Installing emmet-vim"
    cd ~/.vim/bundle && \
    git clone https://github.com/mattn/emmet-vim.git 
    echo "emmet-vim installed successfuly" 
fi

# Install vim-javascript
if [ ! -d ~/.vim/bundle/vim-javascript]; then
    echo "Install vim-javascript"
    git clone https://github.com/pangloss/vim-javascript.git ~/.vim/bundle/vim-javascript
    echo "vim-javascipt installed successfuly" 
fi

# Install vim-jsx
if [ ! -d ~/.vim/bundle/vim-jsx]; then
    echo "Install vim-jsx"
    git clone https://github.com/mxw/vim-jsx.git ~/.vim/bundle/vim-jsx
    echo "vim-javascipt installed successfuly" 
fi

# Install ale
if [ ! -d ~/.vim/bundle/ale ]; then
    echo "Install vim-ale"
    cd ~/.vim/bundle && \
    git clone https://github.com/w0rp/ale.git
    echo "vim-ale installed successfuly" 
fi

# Install vim-es2015-snippets
if [ ! -d ~/.vim/bundle/vim-es2015-snippets ]; then
    echo "Install vim-es2015-snippets"
    cd ~/.vim/bundle && \
    git clone https://github.com/epilande/vim-es2015-snippets.git
    echo "vim-es2015-snippets installed successfuly" 
fi

# Install vim-react-snippets
if [ ! -d ~/.vim/bundle/vim-react-snippets ]; then
    echo "Install vim-react-snippets"
    cd ~/.vim/bundle && \
    git clone https://github.com/epilande/vim-react-snippets.git
    echo "vim-react-snippets installed successfuly" 
fi

# Install tmux
if [ ! -f /usr/local/bin/tmux ]; then
    echo "Install tmux"
    brew install tmux
    echo "tmux installed successfuly"
fi

# Install syntastic
if [ ! -d ~/.vim/bundle/vim-syntastic ]; then
    echo "Install syntastic"
    cd ~/.vim/bundle && \
    git clone --depth=1 https://github.com/vim-syntastic/syntastic.git
    echo "syntastic installed successfuly"
fi

# Install fixmyjs
if [ ! -d ~/.vim/bundle/vim-fixmyjs ]; then
    echo "Install vim-fixmyjs"
    cd ~/.vim/bundle && \
    git clone https://github.com/ruanyl/vim-fixmyjs.git
    echo "vim-fixmyjs installed successfuly"
fi
